version: '3.9'
services:
  killgrave:
    image: friendsofgo/killgrave:0.4.1
    working_dir: /app
    command: -config config.yml
    ports:
      - 8090:80
    volumes:
      - ./killgrave/error:/app
  vector:
    image: timberio/vector:0.42.0-alpine
    # image: timberio/vector:latest-alpine - Uncomment this if tag no longer exists
    depends_on:
      killgrave:
        condition: service_started
    ports:
      - 8686:8686
    command: ["-c", "/etc/vector/vector.toml"]
    environment:
      - DD_SITE
      - DD_API_KEY
      - LOG=info
    volumes:
      - ./vector:/etc/vector:ro
